adminapp/urls.py
from django.urls import re_path

import adminapp.views as adminapp

from .apps import AdminappConfig

app_name = AdminappConfig.name

urlpatterns = [
    re_path(r"^$", adminapp.admin_main, name="admin_main"),
    re_path(r"^users/create/$", adminapp.user_create, name="user_create"),
    re_path(r"^users/read/$", adminapp.UsersListView.as_view(), name="users"),
    re_path(r"^users/update/(?P<pk>\d+)/$", adminapp.user_update, name="user_update"),
    re_path(r"^users/delete/(?P<pk>\d+)/$", adminapp.user_delete, name="user_delete"),
    re_path(r"^users/blocked/(?P<pk>\d+)/$", adminapp.user_blocked, name="user_blocked"),
    re_path(r"^users/unblocked/(?P<pk>\d+)/$", adminapp.user_unblocked, name="user_unblocked")

]

authapp/urls.py
from django.urls import path

import authapp.views as authapp


app_name = 'auth'

urlpatterns = [
    path('login/', authapp.LoginView.as_view(), name='login'),
    path('logout/', authapp.LogoutView.as_view(), name='logout'),
    path('register/', authapp.RegisterView.as_view(), name='register'),
    path('edit/', authapp.UserEditView.as_view(), name='edit'),
    path('notifications/', authapp.NotificationView.as_view(), name='notifications'),
    path('blocked/', authapp.BlockedView.as_view(), name='blocked'),
    path('notifications_live/<int:count>/', authapp.notifications_live, name='notifications_live'),
    path('messages_live/<int:count>/', authapp.messages_live, name='messages_live'),
]

intergalactic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path



urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('profile/', include('userprofile.urls', namespace='profile')),
    path('blog_admin/', include('adminapp.urls', namespace='adminapp')),
    path('moderation/', include('moderation.urls', namespace='moderation')),
    path('moneyapp/', include('moneyapp.urls', namespace='moneyapp')),
    path('', include('social_django.urls', namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

from .views import Main, Articles, ArticlePage, Search

urlpatterns = [
    path('', Main.as_view(), name='main'),
    path('articles/<int:pk>/', Articles.as_view(), name='hub_category'),
    path('article_page/<int:pk>/', ArticlePage.as_view(), name='article_page'),
    path('comment/<int:pk>/', mainapp.like_dislike_comment, name='comments'),
    path('search/', Search.as_view(), name='search'),
    path('set_sorting/<str:sorting_type>/', mainapp.set_sorted_type, name='set_sorting'),
]

userprofile/urls.py
from django.urls import path

import userprofile.views as profile


app_name = 'profile'

urlpatterns = [
    path('', profile.UserProfileView.as_view(), name='main'),
    path('create_article/', profile.ArticleCreationView.as_view(), name='create_article'),
    path('change_active/<int:article_pk>/', profile.ArticleChangeActiveView.as_view(), name='change_active'),
    path('edit_article/<int:pk>/', profile.ArticleEditView.as_view(), name='edit_article'),
    path('send_to_moderation/<int:pk>/', profile.SendToModeration.as_view(), name='send_to_moderation'),
    path('draft_article/<int:pk>/', profile.DraftArticle.as_view(), name='draft_article'),
    path('user/<int:pk>/', profile.OtherUserProfile.as_view(), name='user'),
    path('correspondence/', profile.CorrespondenceView.as_view(), name='correspondence'),
    path('get_messages/<int:pk>', profile.Messages.as_view(), name='get_messages'),
    path('new_message/', profile.Messages.as_view(), name='new_messages'),
    path('new_chat/<int:pk>', profile.CreateChat.as_view(), name='new_chat'),
    path('task/<int:chat>', profile.get_new_messages, name='task'),
]

mainapp/forms.py
from django_summernote.fields import SummernoteTextFormField, SummernoteTextField
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from django.forms import ModelForm

from mainapp.models import Article
from django import forms


class ArticleCreationForm(ModelForm):
    class Meta:
        model = Article
        fields = ['name', 'preview', 'text', 'tag', 'hub', 'image']
        widgets = {
            'text': SummernoteWidget(),
        }

    def __init__(self, *args, **kwargs):
        super(ArticleCreationForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            if field_name in ['name', 'preview', 'hub']:
                field.required = True
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['style'] = 'width: 1000px;'


class CommentForm(forms.Form):
    comment = forms.CharField(label='comment', max_length=1000)

mainapp/services/activity/views.py
from mainapp.models import Visits


def view_views(self):
    """Показывает просмотры"""
    user_ip = self.request.get_host()
    if self.request.user.is_authenticated:
        user_name = self.request.user.username
    else:
        user_name = "Anon"
    self.object = self.get_object()
    if Visits.objects.filter(article=self.object, host=user_ip, user=user_name):
        return None
    else:
        self.object.views += 1
        Visits.objects.create(article=self.object, user=user_name, host=user_ip)
        self.object.save()

mainapp/views.py
from compat import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import View, ListView, DetailView, CreateView
from django.http import HttpResponseRedirect, Http404, JsonResponse
from django.urls import reverse_lazy, reverse
from django.utils.translation import gettext as _
from authapp.models import NotificationModel, IntergalacticUser
from mainapp.models import Article, ArticleStatus, VoiceArticle

from mainapp.forms import ArticleCreationForm, CommentForm
from moneyapp.services.moneys import make_donations

from mainapp.models import Article, ArticleStatus, Sorting
from mainapp.forms import ArticleCreationForm, CommentForm
from mainapp.models import Comment
from mainapp.services.activity.likes import LikeDislike

from .services.search_filter import ArticleFilter
from .services.articlepage.get import get_article_page, if_get_ajax
from .services.articlepage.post import post_article_page
from .services.audio import play_text
from .services.sorting import get_sorted_queryset
# from moneyapp.models import Transaction # конфликт при слиянии ie-173, на всякий случай пока просто закомментил
from .services.activity.comment import add_comment_complaint, add_article_complaint
from .services.mainpage.get_context import get_context_main_page


class Main(ListView):
    """ CBV Главной страницы """
    model = Article
    template_name = 'mainapp/index.html'
    extra_context = {'title': 'Главная'}

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return get_context_main_page(self, context)


class Articles(ListView):
    """ CBV хабов страницы """
    model = Article
    template_name = 'mainapp/articles.html'
    extra_context = {'title': 'Статьи'}
    context_object_name = 'articles'
    paginate_by = 5

    def get_queryset(self):
        status = ArticleStatus.objects.get(name='Опубликована')
        if self.kwargs["pk"] == 0:
            article = Article.objects.filter(article_status_new=status)
        else:
            article = Article.objects.filter(
                article_status_new=status, hub=self.kwargs["pk"])

        return get_sorted_queryset(self, article)


class ArticlePage(DetailView):
    """CBV одной статьи"""
    template_name = 'mainapp/article_page.html'
    model = Article
    extra_context = {
        'page_title': 'Статья',
        'CommentForm': CommentForm,
    }

    def get(self, request, *args, **kwargs):
        # Сбор контекста и взаимодействие активити
        context = get_article_page(self)

        # Проверка на аякс
        if self.request.is_ajax():
            return if_get_ajax(self, context)

        # Рендер обычного гет запроса
        return self.render_to_response(context)

    def post(self, *args, **kwargs):
        # Взаимодействие активити
        post_article_page(self)

        # Рендер обычного гет запроса

        if 'donation' in self.request.POST.dict():
            make_donations(self, self.request.POST)
        if 'comment_complaint' in self.request.POST.dict():
            add_comment_complaint(
                self.request.user.id, self.request.POST['comment_complaint'], self.request.POST['text_complaint'])
        if 'article_complaint' in self.request.POST.dict():
            print(self.request.POST)
            add_article_complaint(
                self.request.user.id, self.request.POST['article_complaint'], self.request.POST['text_complaint'])

        return HttpResponseRedirect(reverse_lazy('article_page', args=(int(self.kwargs["pk"]),)))


class ArticleCreationView(CreateView):
    """CBV для создание статьи"""
    model = Article
    form_class = ArticleCreationForm
    success_url = reverse_lazy('auth:profile')

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.article_status_new = ArticleStatus.objects.get(
            name='Черновик')
        self.object.save()
        return super().form_valid(form)


class ArticleChangeActiveView(View):
    """CBV для активации статьи"""

    def post(self, request, article_pk):
        target_article = get_object_or_404(Article, pk=article_pk)
        target_article.is_active = False if target_article.is_active else True

        if target_article.article_status_new.name == 'В архиве':
            target_article.article_status_new = ArticleStatus.objects.get(
                name='Черновик')
        else:
            target_article.article_status_new = ArticleStatus.objects.get(
                name='В архиве')

        target_article.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ArticleEditView(View):
    """Контроллер для изменения статьи"""
    title = 'Редактирование статьи'
    template_name = 'mainapp/edit_article.html'
    form_class = ArticleCreationForm
    redirect_to = 'auth:profile'

    def get(self, request, pk):
        context = {
            'form': self.form_class(instance=Article.objects.get(pk=pk)),
            'article': Article.objects.get(pk=pk)
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        article = Article.objects.get(pk=pk)
        article_form = ArticleCreationForm(
            data=request.POST, files=request.FILES, instance=article)
        if article_form.is_valid():
            article_form.save()
            if article.article_status_new == ArticleStatus.objects.get(name='Опубликована'):
                article.article_status_new = ArticleStatus.objects.get(
                    name='На модерации')
                article.save()

        return HttpResponseRedirect(reverse(self.redirect_to))


class SendToModeration(View):
    def post(self, request, pk):
        article = Article.objects.get(pk=pk)
        article.article_status_new = ArticleStatus.objects.get(
            name='На модерации')
        play_text(pk)
        article.save()
        return HttpResponseRedirect(reverse('auth:profile'))


class DraftArticle(View):
    def post(self, request, pk):
        article = Article.objects.get(pk=pk)
        article.article_status_new = ArticleStatus.objects.get(name='Черновик')
        article.save()
        return HttpResponseRedirect(reverse('auth:profile'))


class Search(ListView):
    # model = Article
    template_name = 'mainapp/articles.html'
    extra_context = {'title': 'Поиск'}
    paginate_by = 5

    def get_queryset(self, article):
        return get_sorted_queryset(self, article)

    def get(self, request, page_num=1, *args, **kwargs):
        article = Article.objects.filter(
            article_status_new=ArticleStatus.objects.get(name='Опубликована'))
        search_filter = ArticleFilter(request.GET, queryset=article)
        article = search_filter.qs
        self.object_list = self.get_queryset(article)
        allow_empty = self.get_allow_empty()

        if not allow_empty:
            # When pagination is enabled and object_list is a queryset,
            # it's better to do a cheap query than to load the unpaginated
            # queryset in memory.
            if self.get_paginate_by(self.object_list) is not None and hasattr(self.object_list, 'exists'):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list
            if is_empty:
                raise Http404(_('Empty list and “%(class_name)s.allow_empty” is False.') % {
                    'class_name': self.__class__.__name__,
                })
        context = self.get_context_data()
        context['search_filter'] = search_filter
        context['filter'] = request.GET.dict()
        return render(request, 'mainapp/articles.html', context)


def set_sorted_type(request, sorting_type):
    sorting = Sorting.objects.all()
    if request.user.is_anonymous:
        request.session['sorting'] = sorting_type
    else:
        sorting_by_user = sorting.filter(user=request.user.id)
        sorting_by_user.update(sorting_type=sorting_type)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def like_dislike_comment(request, pk):
    get_dict = request.GET.dict()
    comment = Comment.objects.get(pk=pk)
    like_dislike = LikeDislike(
        comment.author, comment.article, get_dict.get('status'), comment=comment)
    like_dislike.status_like()
    like_dislike.define_count_like()
    return JsonResponse({"count_like": comment.count_like,
                         "count_dislike": comment.count_dislike,
                         "status": like_dislike.like.status})

mainapp/templates/mainapp/includes/inc__footer.html
{% load static %}

<div class="footer">
    <nav class="navbar navbar-expand-lg navbar-light bg-footer" style="bottom: 0; width: 100%">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'hub_category' 0 %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'hub_category' 0 %}">Все хабы</a>
                </li>
            </ul>
            <span class="nav-item" style="color: dimgrey">HoneyBadgers&#169 - 2021</span>
        </div>
    </nav>
</div>

mainapp/templates/mainapp/includes/inc__main_menu.html
{% load static %}
<div class="sticky-top">
    <nav class="navbar navbar-expand-lg navbar-light {% if request.user.is_authenticated %}username{% endif %} ">
        <a class="navbar-brand" href="{% url 'main' %}">
            <img src="{% static 'img/logo.png' %}" width="40" height="40" class="d-inline-block align-top" alt="">
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main' %}">Главная</a>
                </li>
                   <li class="nav-item">
                       {% include 'mainapp/includes/inc__search.html' %}
                   </li>
            </ul>
            {% if user.is_superuser %}
                <div class="user-panel admin-moder-panel">
                    <div class="menu-icon-box margin1">
                        <a id="menu-icon" href="{% url 'adminapp:users' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                              <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                              <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
                              <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
                            </svg>
                            {% if transactions_not_read_count %}
                                <span class="badge transaction-icon">{{ transactions_not_read_count }}</span>
                            {% endif %}
                        </a>

                    </div>
                    <div class="menu-icon-box">
                        <a id="menu-icon" href="{% url 'moderation:main' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-clipboard-check" viewBox="0 0 16 16">
                              <path fill-rule="evenodd" d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                              <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                              <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
                            </svg>
                        </a>
                    </div>
                </div>
            {% elif user.is_staff %}
                <div class="user-panel admin-moder-panel">
                    <div class="menu-icon-box">
                        <a id="menu-icon" href="{% url 'moderation:main' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-clipboard-check" viewBox="0 0 16 16">
                              <path fill-rule="evenodd" d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                              <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                              <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
                            </svg>
                        </a>
                    </div>
                </div>
            {% endif %}
            <div class="user-panel">
                {% if user.is_authenticated %}
                    <a class="user-panel-button" title="Сообщения" href="{% url 'profile:correspondence' %}">
{#                        {% if False %}#}
{#                            <div class="menu-icon-box" style="margin-right: 20px">#}
{#                                <svg id="menu-icon" xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">#}
{#                                  <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>#}
{#                                </svg>#}
{#                                <span class="badge notification-icon">0</span>#}
{#                            </div>#}
{#                        {% else %}#}
                            <div class="menu-icon-box" style="margin-right: 20px">
                                <svg id="menu-icon" xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-chat-left-text messages" viewBox="0 0 16 16">
                                  <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                  <path d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
                                </svg>
                            </div>
{#                        {% endif %}#}
                    </a>
                    <a class="user-panel-button" title="Уведомления" href="{% url 'auth:notifications' %}">
{#                        {% if notifications_not_read %}#}
{#                            <div class="menu-icon-box">#}
{#                                <svg id="menu-icon" xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-bell-fill notification" viewBox="0 0 16 16">#}
{#                                    <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>#}
{#                                </svg>#}
{#                                {% if request.resolver_match.url_name == 'notifications' %}#}
{#                                <span id="icon-count" class="badge notification-icon">{{ notifications_not_read.count }}</span>#}
{#                                {% else %}#}
{#                                <span class="badge notification-icon">{{ notifications_not_read }}</span>#}
{#                                {% endif %}#}
{#                            </div>#}
{#                        {% else %}#}
                            <div class="menu-icon-box">
                                <svg id="menu-icon"  xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-bell notification" viewBox="0 0 16 16">
                                    <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
                                </svg>
                            </div>
{#                        {% endif %}#}
                    </a>
                    <div class="menu-icon-box">
                        <a id="menu-icon" class="user-panel-button" title="Личный кабинет" href="{% url 'profile:main' %}">
                        <svg width="25" height="25" viewBox="0 0 16 16" class="bi bi-person-fill" fill="currentColor"
                             xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                  d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                        </svg>
                        {{ user.username }}
                        </a>
                    </div>
                    <a class="user-panel-button" href="{% url 'auth:logout' %}">
                        Выход
                    </a>
                {% else %}
                    <a class="user-panel-button" href="{% url 'auth:login' %}">
                        Вход
                    </a>
                    <a class="user-panel-button" href="{% url 'auth:register' %}">
                        Регистрация
                    </a>
                {% endif %}
            </div>
        </div>
    </nav>
    <nav>
    <div>
        <ul class="menu_category nav-pills d-flex justify-content-center">
            <li {% if request.resolver_match.url_name == "hub_category" and not request.resolver_match.kwargs.pk %} class="active" {% endif %}>
            <a class="nav-link black" href="{% url 'hub_category' 0 %}">Все хабы</a>
            </li>
            {% for item in category_menu %}
            <li {% if request.resolver_match.kwargs.pk == item.pk and "hub_category" == request.resolver_match.url_name  %} class="active" {% endif %}>
            <a class="nav-link black" href="{% url 'hub_category' item.pk %}">{{ item.name }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    </nav>
</div>

mainapp/templates/mainapp/includes/inc__pagination.html
{% load static %}
{% if page_obj.has_other_pages %}
<nav class="nav-page">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item ">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}&
                {%if 'author' in request.GET %}name={{filter.name}}
                &text={{filter.text}}&author={{filter.author}}&hub={{filter.hub}}&start_date={{filter.start_date}}
                &end_date={{filter.end_date}}&rating_start={{filter.rating_start}}&rating_end={{filter.rating_end}}
                {%endif%}">&larr; Предыдущая</a>
        </li>
        {% endif %}
        {% for page in paginator.page_range %}
        {% if page_obj.number == page %}
        <li class="page-item active" aria-current="page">
            <a class="page-link">{{ page }}</a>
        </li>
        {% elif page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page }}&{%if 'author' in request.GET %}name={{filter.name}}
               &text={{filter.text}}&author={{filter.author}}&hub={{filter.hub}}&start_date={{filter.start_date}}
               &end_date={{filter.end_date}}&rating_start={{filter.rating_start}}&rating_end={{filter.rating_end}}
               {%endif%}">{{ page }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link"
               href="?page={{ page_obj.next_page_number }}&{%if 'author' in request.GET %}name={{filter.name}}
               &text={{filter.text}}&author={{filter.author}}&hub={{filter.hub}}&start_date={{filter.start_date}}
               &end_date={{filter.end_date}}&rating_start={{filter.rating_start}}&rating_end={{filter.rating_end}}
               {%endif%}">
                Следующая &rarr; </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}