adminapp/urls.py
from django.urls import re_path

import adminapp.views as adminapp

from .apps import AdminappConfig

app_name = AdminappConfig.name

urlpatterns = [
    re_path(r"^$", adminapp.admin_main, name="admin_main"),
    re_path(r"^users/create/$", adminapp.user_create, name="user_create"),
    re_path(r"^users/read/$", adminapp.UsersListView.as_view(), name="users"),
    re_path(r"^users/update/(?P<pk>\d+)/$", adminapp.user_update, name="user_update"),
    re_path(r"^users/delete/(?P<pk>\d+)/$", adminapp.user_delete, name="user_delete"),
    re_path(r"^users/blocked/(?P<pk>\d+)/$", adminapp.user_blocked, name="user_blocked"),
    re_path(r"^users/unblocked/(?P<pk>\d+)/$", adminapp.user_unblocked, name="user_unblocked")

]

authapp/urls.py
from django.urls import path

import authapp.views as authapp


app_name = 'auth'

urlpatterns = [
    path('login/', authapp.LoginView.as_view(), name='login'),
    path('logout/', authapp.LogoutView.as_view(), name='logout'),
    path('register/', authapp.RegisterView.as_view(), name='register'),
    path('edit/', authapp.UserEditView.as_view(), name='edit'),
    path('notifications/', authapp.NotificationView.as_view(), name='notifications'),
    path('blocked/', authapp.BlockedView.as_view(), name='blocked'),
    path('notifications_live/<int:count>/', authapp.notifications_live, name='notifications_live'),
    path('messages_live/<int:count>/', authapp.messages_live, name='messages_live'),
]

intergalactic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path



urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('profile/', include('userprofile.urls', namespace='profile')),
    path('blog_admin/', include('adminapp.urls', namespace='adminapp')),
    path('moderation/', include('moderation.urls', namespace='moderation')),
    path('moneyapp/', include('moneyapp.urls', namespace='moneyapp')),
    path('', include('social_django.urls', namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

moderation/urls.py
from django.urls import path
from moderation.views import Moderator, ModerationArticleView, RegisterNewMessage, ApproveArticle, RejectArticle, ModerateComplaints, ModerationArticleComplaintView, RegisterNewComplaintMessage

from moderation.views import BlockedArticle

app_name = 'moderation'

urlpatterns = [
    path('', Moderator.as_view(), name='main'),
    path('article/<int:pk>/', ModerationArticleView.as_view(), name='article'),
    path('new_message/', RegisterNewMessage.as_view(), name='new_message'),
    path('approve_article/<int:pk>/',
         ApproveArticle.as_view(), name='approve_article'),
    path('reject_article/<int:pk>/',
         RejectArticle.as_view(), name='reject_article'),
    path('blocked_article/<int:pk>/', BlockedArticle.as_view(), name='blocked_article'),
    path('new_complaint_message/', RegisterNewComplaintMessage.as_view(),
         name='new_complaint_message'),
    path('complaints', ModerateComplaints.as_view(), name='complaints'),
    path('complaint/<int:pk>/',
         ModerationArticleComplaintView.as_view(), name='complaint'),

]

userprofile/urls.py
from django.urls import path

import userprofile.views as profile


app_name = 'profile'

urlpatterns = [
    path('', profile.UserProfileView.as_view(), name='main'),
    path('create_article/', profile.ArticleCreationView.as_view(), name='create_article'),
    path('change_active/<int:article_pk>/', profile.ArticleChangeActiveView.as_view(), name='change_active'),
    path('edit_article/<int:pk>/', profile.ArticleEditView.as_view(), name='edit_article'),
    path('send_to_moderation/<int:pk>/', profile.SendToModeration.as_view(), name='send_to_moderation'),
    path('draft_article/<int:pk>/', profile.DraftArticle.as_view(), name='draft_article'),
    path('user/<int:pk>/', profile.OtherUserProfile.as_view(), name='user'),
    path('correspondence/', profile.CorrespondenceView.as_view(), name='correspondence'),
    path('get_messages/<int:pk>', profile.Messages.as_view(), name='get_messages'),
    path('new_message/', profile.Messages.as_view(), name='new_messages'),
    path('new_chat/<int:pk>', profile.CreateChat.as_view(), name='new_chat'),
    path('task/<int:chat>', profile.get_new_messages, name='task'),
]

userprofile/models.py
from django.db import models

from authapp.models import IntergalacticUser


class ButtonsInProfile(models.Model):
    name = models.CharField(verbose_name='название кнопки', max_length=20)
    include_html_file_name = models.CharField(verbose_name='html файл', max_length=100)


class Chat(models.Model):
    user = models.ManyToManyField(IntergalacticUser)


class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, verbose_name='Чат')
    author = models.ForeignKey(
        IntergalacticUser,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='от пользователя'
    )
    text = models.TextField(verbose_name='Текст сообщения')
    datetime = models.DateTimeField(verbose_name='дата сообщения', auto_now_add=True)
    read = models.BooleanField(verbose_name='Прочитано', default=False)
    was_call = models.BooleanField(default=False)  # Если сообщение отображалось где-либо хотя-бы раз, то True


class NewMessage(models.Model):
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    to_user = models.ForeignKey(IntergalacticUser, on_delete=models.CASCADE)

userprofile/views.py
import json
import locale
import pytz

from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic import View, CreateView
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse

from authapp.models import IntergalacticUser, NotificationModel
from authapp.services.notifications import Notification
from mainapp.models import Article, ArticleStatus
from mainapp.forms import ArticleCreationForm
from mainapp.services.audio import play_text
from moneyapp.models import UserBalance
from moneyapp.models import Transaction
from userprofile.models import Message, Chat, NewMessage

from time import sleep
from datetime import timedelta


class UserProfileView(View):
    title = 'личный кабинет'
    template_name = 'userprofile/profile.html'

    def get_context_data(self, request):
        statuses = ArticleStatus.objects.all()
        articles_with_status = {}
        for status in statuses:
            articles_with_status[status] = Article.objects.filter(
                author=self.request.user,
                article_status_new=status
            )

        context = {
            'title': self.title,
            'user': self.request.user,
            'creation_form': ArticleCreationForm(),
            'articles': articles_with_status,
            'notifications_not_read': NotificationModel.objects.filter(is_read=0,
                                                                         recipient=self.request.user.id).count(),
            'balance': round(UserBalance.objects.filter(user_id=self.request.user.id).first().amount,2),
            'transactions_not_read': Transaction.objects.filter(is_read=False, status='CREATED'),
            'transactions_not_read_count': Transaction.objects.filter(is_read=False, status='CREATED').count(),
        }
        return context

    def post(self, request):
        data = request.POST
        send_to_email_value = True if data.dict()['value_checkbox'] == "true" else False
        current_user = IntergalacticUser.objects.filter(id=request.user.id).first()
        current_user.send_to_email = send_to_email_value
        current_user.save()
        return JsonResponse({'status': 'success'})

    def get(self, request):
        if not UserBalance.objects.filter(user_id=request.user.id):
            new_balance = UserBalance.objects.create(user_id=request.user.id)
            new_balance.save()
        return render(request, self.template_name, self.get_context_data(request))


class ArticleCreationView(CreateView):
    """CBV для создание статьи"""
    model = Article
    form_class = ArticleCreationForm
    success_url = reverse_lazy('profile:main')

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.article_status_new = ArticleStatus.objects.get(name='Черновик')
        self.object.save()
        return super().form_valid(form)


class ArticleChangeActiveView(View):
    """CBV для активации статьи"""

    def post(self, request, article_pk):
        target_article = get_object_or_404(Article, pk=article_pk)
        target_article.is_active = False if target_article.is_active else True

        if target_article.article_status_new.name == 'В архиве':
            target_article.article_status_new = ArticleStatus.objects.get(name='Черновик')
        else:
            target_article.article_status_new = ArticleStatus.objects.get(name='В архиве')
            notification = Notification(target_article, context='archive')
            notification.send()

        target_article.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class SendToModeration(View):
    def post(self, request, pk):
        article = Article.objects.get(pk=pk)
        article.article_status_new = ArticleStatus.objects.get(name='На модерации')
        if request.user.rating_author >= 7:
            article.article_status_new = ArticleStatus.objects.get(name='Опубликована')
            notification = Notification(article, context='published')
            notification.send()
        article.save()
        play_text(pk)
        notification = Notification(article, context='moderation')
        notification.send()
        return HttpResponseRedirect(reverse('profile:main'))


class ArticleEditView(View):
    """Контроллер для изменения статьи"""
    title = 'Редактирование статьи'
    template_name = 'mainapp/edit_article.html'
    form_class = ArticleCreationForm
    redirect_to = 'profile:main'

    def get(self, request, pk):
        context = {
            'form': self.form_class(instance=Article.objects.get(pk=pk)),
            'article': Article.objects.get(pk=pk),
            'notifications_not_read': NotificationModel.objects.filter(is_read=0,
                                                                       recipient=self.request.user.id).count()
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        article = Article.objects.get(pk=pk)
        article_form = ArticleCreationForm(
            data=request.POST, files=request.FILES, instance=article)
        if article_form.is_valid():
            article_form.save()
            if article.article_status_new == ArticleStatus.objects.get(name='Опубликована'):
                article.article_status_new = ArticleStatus.objects.get(name='На модерации')
                article.save()
                notification = Notification(article, context='moderate_after_edit')
                notification.send()

        return HttpResponseRedirect(reverse(self.redirect_to))


class DraftArticle(View):
    def post(self, request, pk):
        article = Article.objects.get(pk=pk)
        article.article_status_new = ArticleStatus.objects.get(name='Черновик')
        article.save()
        return HttpResponseRedirect(reverse('profile:main'))


class OtherUserProfile(View):
    template_name = 'userprofile/other_user.html'
    
    def get(self, request, pk):
        if request.user == IntergalacticUser.objects.get(pk=pk):
            return HttpResponseRedirect(reverse('profile:main'))

        context = {
            'target_user': get_object_or_404(IntergalacticUser, pk=pk),
            'articles': Article.objects.filter(
                author=IntergalacticUser.objects.get(pk=pk),
                article_status_new=ArticleStatus.objects.get(name='Опубликована')
            )
        }
        return render(request, self.template_name, context)


class CorrespondenceView(View):

    def get_context_data(self, request):
        chats = self.get_chats(request)
        context = {
            'chats': chats
        }
        return context

    def get(self, request):
        return render(request, 'userprofile/correspondence.html', context=self.get_context_data(request))

    @staticmethod
    def get_chats(request):
        chats = Chat.objects.filter(user=request.user)
        members_and_last_messages = []
        for chat in chats:
            for user in chat.user.all():
                if user != request.user:
                    members_and_last_messages.append({
                        'chat_item': chat,
                        'member': user,
                        'last_message': Message.objects.filter(chat=chat).last(),
                        'not_read': Message.objects.filter(chat=chat, read=False).exclude(author=request.user).count(),
                    })

        return members_and_last_messages


class Messages(View):
    def get(self, request, pk):
        """Получить все сообщения чата и отрендерить их"""
        if request.is_ajax():
            chat = Chat.objects.get(pk=pk)
            messages = Message.objects.filter(chat=chat).order_by('datetime')
            for msg in messages:
                msg.was_call = True
                msg.read = True
                msg.save()

            context = {'messages': messages}

            new_messages = NewMessage.objects.filter(to_user=request.user)
            for msg in new_messages:
                msg.delete()
            return render(request, 'userprofile/messages.html', context)

    def post(self, request):
        locale.setlocale(locale.LC_ALL, "")
        """Сохранить новое сообщение"""
        if request.is_ajax():
            ajax = json.loads(request.body.decode('utf-8'))
            chat = Chat.objects.get(pk=ajax.get('chat'))
            message = Message(
                chat=chat,
                author=request.user,
                text=ajax.get('text')
            )
            message.save()
            users_in_chat = chat.user.all()
            for user in users_in_chat:
                if user != request.user:
                    new_msg = NewMessage(message=message, to_user=user)
                    new_msg.save()

            msg_datetime = message.datetime + timedelta(hours=3)
            msg_datetime = msg_datetime.strftime('%d %B %Y г. %H:%M')

            result = {
                'datetime': msg_datetime,
                'text': message.text,
                'chat': ajax.get('chat')
            }
            return JsonResponse(result)


class CreateChat(View):
    def get(self, request, pk):
        addressee = IntergalacticUser.objects.get(pk=pk)
        if not Chat.objects.filter(user=request.user).filter(user=addressee):
            chat = Chat()
            chat.save()
            request.user.chat_set.add(chat)
            addressee.chat_set.add(chat)
        return HttpResponseRedirect(reverse('profile:correspondence'))


def get_new_messages(request, chat):
    locale.setlocale(locale.LC_ALL, "")
    for _ in range(30):
        messages = NewMessage.objects.filter(to_user=request.user)
        if messages:
            result = {
                'msgs': [],
                'chats': {},
            }
            for msg in messages:

userprofile/templates/userprofile/correspondence.html
{% extends "mainapp/base.html" %}
{% load static %}
{% block title %}{{ title|title }} {% endblock %}
{% load project_tags %}
{% block stylesheets %}
    {% include 'mainapp/includes/inc_stylesheets.html' %}
    <link rel="stylesheet" href="{% static 'css/correspondence.css' %}" type="text/css">
{% endblock stylesheets %}
{% block js %}

{% endblock %}
{% block content %}
    {% csrf_token %}
    <h3 class=" text-center">Messaging</h3>
    <div class="container">
        <div class="messaging">
            <div class="inbox_msg">
                <div class="inbox_people">
                    <div class="headind_srch">
                        <div class="recent_heading">
                            <h4>Recent</h4>
                        </div>
                    </div>
                    <div class="inbox_chat">
                        {% if chats %}
                            {% for chat in chats %}
                                <div class="chat_list" id="{{ chat.chat_item.pk }}">
                                    <div class="chat_people" id="{{ chat.chat_item.pk }}">
                                        <div class="chat_img">
                                            <img src="
                                                {{ chat.member.avatar|media_folder_users }}
                                                " alt="sunil" id="{{ chat.chat_item.pk }}
                                                ">
                                        </div>
                                        <div class="chat_ib" id="{{ chat.chat_item.pk }}">
                                            <h5 id="{{ chat.chat_item.pk }}">
                                                {{ chat.member.username }}
                                                <div class="not_read" id="{{ chat.chat_item.pk }}">
                                                    {% if chat.not_read %}
                                                    <p class="not_readd" id="{{ chat.chat_item.pk }}">{{ chat.not_read }}</p>
                                                    {% endif %}
                                                </div>
                                                <span class="chat_date" id="{{ chat.chat_item.pk }}">{{ chat.last_message.datetime }}</span>
                                            </h5>
                                            <p class='last_message' style="min-width: 400px" id="{{ chat.chat_item.pk }}">
                                                {% if chat.last_message %}
                                                    {{ chat.last_message.text }}
                                                {% else %}
                                                    (нет сообщений)
                                                {% endif %}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <p>У вас пока нет ни одного чата</p>
                        {% endif %}

                    </div>
                </div>
                <div class="mesgs">
                    <div class="msg_history">
                        <div class="no_msg"><h1>Выберете чат</h1></div>
                    </div>
                    <div class="type_msg">
                        <div class="input_msg_write">
                            <input disabled type="text" class="write_msg" placeholder="Текст сообщения"/>
                            <button class="msg_send_btn" type="button">
                                ->
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/chat.js' %}"></script>
{% endblock %}

userprofile/templates/userprofile/messages.html
{% load project_tags %}
{% for message in messages %}
    {% if user == message.author %}
        <div class="outgoing_msg message" id="{{ message.pk }}">
            <div class="sent_msg">
                <p>{{ message.text }}</p>
                <span class="time_date">{{ message.datetime }}</span>
            </div>
        </div>
    {% else %}
        <div class="incoming_msg message" id="{{ message.pk }}">
            <div class="incoming_msg_img"><img src="{{ message.author.avatar|media_folder_users }}" alt="sunil"></div>
            <div class="received_msg">
                <div class="received_withd_msg">
                    <p>{{ message.text }}</p>
                    <span class="time_date">{{ message.datetime }}</span>
                </div>
            </div>
        </div>
    {% endif %}
{% endfor %}

userprofile/templates/userprofile/profile.html
{% extends "mainapp/base.html" %}
{% load static %}
{% block title %}{{ title|title }} {% endblock %}
{% load project_tags %}
{% block content %}
    <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
    <div class="article-box">
        <div class="details">
            <h3 class="text-center profile_subheading_1">Личный кабинет</h3>
            <div class="block-article">
                <div class="block-profile">
                    <div class="img-role-redaction-block">
                        <div class="profile-img-block">
                            <img class="profile_image" src="{{ user.avatar|media_folder_users }}"
                                 alt="profile_image">
                        </div>
                        <div class="profile-role-block">
                            {% if user.is_superuser %}
                                Администратор
                            {% elif user.is_staff %}
                                Модератор
                            {% else %}
                                Пользователь
                            {% endif %}
                        </div>
                        <div class="user-admin-moder-buttons">
                            <div class="user-balance-box">
                                <p>
                                    <span>Баланс: {{ balance }}</span>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-cash-coin" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
                                        <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
                                        <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
                                        <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
                                    </svg>
                                </p>
                            </div>
                            <a class="btn-red-profile-block" href="{% url 'auth:edit' %}">
                                Редактировать профиль
                            </a>
                            <a class="btn-red-profile-block" href="{% url 'profile:correspondence' %}">
                                Переписки
                            </a>
                            Рейтинг автора:
                            <button type="button" class="btn btn-warning">{{user.rating_author| floatformat:2 }}</button>
                            <div class="admin-moder-buttons">
                                {% if user.is_superuser %}
                                    <hr>
                                    <div class="btn-profile-admin-block">
                                        <a class="btn-red-profile-block" href="{% url 'adminapp:users' %}">Админка</a>
                                        <a class="btn-red-profile-block"
                                           href="{% url 'moderation:main' %}">Модерация</a>
                                    </div>
                                {% elif user.is_staff %}
                                    <div><a class="btn btn-secondary" href="{% url 'moderation:main' %}">Модерация</a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="info-about-user">
                        <form action="" method="post">
                        {% csrf_token %}
                            <div class="form-check form-switch">
                                <input class="form-check-input" type="checkbox" name="chk" id="send_email" value="1234" {% if user.send_to_email %} checked {% endif %} >
                                <label class="form-check-label" for="flexSwitchCheckDefault">Получать уведомления на {{ user.email  }}</label>
                            </div>
                        </form>
                        <div class="first-last-name-block">
                            <p class="first-last-name">{{ user.first_name|title }} {{ user.last_name|title }}</p>

                        </div>
                        <hr>
                        <div class="profile_info">
                            <div class="profile_about">
                                <p><span class="about-user-pole">Username:</span> {{ user.username }}</p>
                                <hr>
                                <p><span class="about-user-pole">Возраст:</span> {{ user.age }}</p>
                                <hr>
                                <p><span class="about-user-pole">Обо мне:</span>
                                    {% if user.about_me %}
                                        {{ user.about_me|safe }}
                                    {% else %}
                                        Тут могла бы быть информация о вас, но вы не заполнили профиль =(
                                    {% endif %}
                                </p>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="my-articles">
                <div class="my-articles-item">
                    <h3 class="profile_subheading_1 text-center">
                        Мои статьи
                    </h3>
                </div>
                <div class="my-articles-item">
                    <button type="button" class="btn-create-article" data-toggle="modal" data-target="#createArticle">
                        +
                    </button>
                </div>
            </div>
            <div class="block-article">
                <div class="profile-article">
                    <p class="profile_subheading_2"></p>
                </div>

                <div class="modal fade" id="createArticle" data-backdrop="static" data-keyboard="false" tabindex="-1"
                     aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog modal-xl modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="staticBackdropLabel">Новая статья</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form class="form-horizontal" action="{% url 'profile:create_article' %}" method="post"
                                      enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ creation_form.as_table }}
                                    <br>
                                    <input class="form-control" type="submit" value="Сохранить">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                {% for status, arts in articles.items %}
                    <p class="profile_subheading_2">{{ status.name_plural }}</p>
                    {% if not arts %}
                        <p>Нет статей</p>
                    {% else %}
                        <table class="article-table">
                            <tbody>
                            {% for art in arts %}
                                <tr>
                                    <td class="article-table">
                                        <table>
                                            <tr>
                                                <td rowspan="2" class="article-name">
                                                    {% if art.article_status_new.name == 'Опубликована' %}

                                                        <a href="{% url 'article_page' art.pk %}" class="article-anchor">
                                                            <p>{{ art.name }}</p>
                                                        </a>
                                                    {% elif art.article_status_new.name == 'На модерации' or art.article_status_new.name == 'Требует исправления'  %}
                                                    <a href="{% url 'moderation:article' art.pk %}" class="article-anchor">
                                                        <p>{{ art.name }}</p>
                                                    </a>
                                                    {% else %}
                                                    <p>{{ art.name }}</p>
                                                    {% endif %}

                                                </td>
                                                <td class="hub-name"><p>{{ art.hub.name }}</p></td>
                                                <td rowspan="2" class="article-edit-buttons">
                                                    {% for button in status.buttons.all %}
                                                        {% include button.include_html_file_name %}
                                                    {% endfor %}
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="hub-name"><p>{{ art.add_datetime }}</p></td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <script src="{% static 'js/profile_articles.js' %}"></script>
{% endblock %}