adminapp/urls.py
from django.urls import re_path

import adminapp.views as adminapp

from .apps import AdminappConfig

app_name = AdminappConfig.name

urlpatterns = [
    re_path(r"^$", adminapp.admin_main, name="admin_main"),
    re_path(r"^users/create/$", adminapp.user_create, name="user_create"),
    re_path(r"^users/read/$", adminapp.UsersListView.as_view(), name="users"),
    re_path(r"^users/update/(?P<pk>\d+)/$", adminapp.user_update, name="user_update"),
    re_path(r"^users/delete/(?P<pk>\d+)/$", adminapp.user_delete, name="user_delete"),
    re_path(r"^users/blocked/(?P<pk>\d+)/$", adminapp.user_blocked, name="user_blocked"),
    re_path(r"^users/unblocked/(?P<pk>\d+)/$", adminapp.user_unblocked, name="user_unblocked")

]

authapp/urls.py
from django.urls import path

import authapp.views as authapp


app_name = 'auth'

urlpatterns = [
    path('login/', authapp.LoginView.as_view(), name='login'),
    path('logout/', authapp.LogoutView.as_view(), name='logout'),
    path('register/', authapp.RegisterView.as_view(), name='register'),
    path('edit/', authapp.UserEditView.as_view(), name='edit'),
    path('notifications/', authapp.NotificationView.as_view(), name='notifications'),
    path('blocked/', authapp.BlockedView.as_view(), name='blocked'),
    path('notifications_live/<int:count>/', authapp.notifications_live, name='notifications_live'),
    path('messages_live/<int:count>/', authapp.messages_live, name='messages_live'),
]

intergalactic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path



urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('profile/', include('userprofile.urls', namespace='profile')),
    path('blog_admin/', include('adminapp.urls', namespace='adminapp')),
    path('moderation/', include('moderation.urls', namespace='moderation')),
    path('moneyapp/', include('moneyapp.urls', namespace='moneyapp')),
    path('', include('social_django.urls', namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

from .views import Main, Articles, ArticlePage, Search

urlpatterns = [
    path('', Main.as_view(), name='main'),
    path('articles/<int:pk>/', Articles.as_view(), name='hub_category'),
    path('article_page/<int:pk>/', ArticlePage.as_view(), name='article_page'),
    path('comment/<int:pk>/', mainapp.like_dislike_comment, name='comments'),
    path('search/', Search.as_view(), name='search'),
    path('set_sorting/<str:sorting_type>/', mainapp.set_sorted_type, name='set_sorting'),
]

moderation/urls.py
from django.urls import path
from moderation.views import Moderator, ModerationArticleView, RegisterNewMessage, ApproveArticle, RejectArticle, ModerateComplaints, ModerationArticleComplaintView, RegisterNewComplaintMessage

from moderation.views import BlockedArticle

app_name = 'moderation'

urlpatterns = [
    path('', Moderator.as_view(), name='main'),
    path('article/<int:pk>/', ModerationArticleView.as_view(), name='article'),
    path('new_message/', RegisterNewMessage.as_view(), name='new_message'),
    path('approve_article/<int:pk>/',
         ApproveArticle.as_view(), name='approve_article'),
    path('reject_article/<int:pk>/',
         RejectArticle.as_view(), name='reject_article'),
    path('blocked_article/<int:pk>/', BlockedArticle.as_view(), name='blocked_article'),
    path('new_complaint_message/', RegisterNewComplaintMessage.as_view(),
         name='new_complaint_message'),
    path('complaints', ModerateComplaints.as_view(), name='complaints'),
    path('complaint/<int:pk>/',
         ModerationArticleComplaintView.as_view(), name='complaint'),

]

userprofile/urls.py
from django.urls import path

import userprofile.views as profile


app_name = 'profile'

urlpatterns = [
    path('', profile.UserProfileView.as_view(), name='main'),
    path('create_article/', profile.ArticleCreationView.as_view(), name='create_article'),
    path('change_active/<int:article_pk>/', profile.ArticleChangeActiveView.as_view(), name='change_active'),
    path('edit_article/<int:pk>/', profile.ArticleEditView.as_view(), name='edit_article'),
    path('send_to_moderation/<int:pk>/', profile.SendToModeration.as_view(), name='send_to_moderation'),
    path('draft_article/<int:pk>/', profile.DraftArticle.as_view(), name='draft_article'),
    path('user/<int:pk>/', profile.OtherUserProfile.as_view(), name='user'),
    path('correspondence/', profile.CorrespondenceView.as_view(), name='correspondence'),
    path('get_messages/<int:pk>', profile.Messages.as_view(), name='get_messages'),
    path('new_message/', profile.Messages.as_view(), name='new_messages'),
    path('new_chat/<int:pk>', profile.CreateChat.as_view(), name='new_chat'),
    path('task/<int:chat>', profile.get_new_messages, name='task'),
]

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class IntergalacticUser(AbstractUser):
    sex_male = 'male'
    sex_female = 'female'
    sex_not_selected = 'not selected'
    sex_choices = (
        (sex_male, 'мужской'),
        (sex_female, 'женский'),
        (sex_not_selected, 'не выбран'),
    )
    avatar = models.ImageField(
        verbose_name='Аватарка',
        upload_to='avatars',
        blank=True
    )
    age = models.PositiveSmallIntegerField(
        verbose_name='возраст',
        blank=True,
        null=True
    )
    sex = models.CharField(
        verbose_name='пол',
        max_length=12,
        choices=sex_choices,
        default=sex_not_selected
    )
    send_messages = models.BooleanField(
        default=True,
        verbose_name='Оповещать о новых комментариях'
    )
    send_to_email = models.BooleanField(
        default=True,
        verbose_name='Уведомления на почту'
    )
    about_me = models.TextField(verbose_name='О себе', blank=True, null=True)
    rating_author = models.FloatField(default=0, verbose_name='Рейтинг автора')

    def __str__(self):
        return f'{self.username}'


class NotificationModel(models.Model):
    recipient = models.ForeignKey(IntergalacticUser, on_delete=models.PROTECT,
                                  verbose_name='Получатель', related_name='recipient')
    sender = models.ForeignKey(IntergalacticUser, on_delete=models.PROTECT,
                               verbose_name='Отправитель', related_name='sender', null=True)
    is_read = models.BooleanField(default=False, db_index=True,
                                  verbose_name='Статус прочтения')
    action = models.TextField(verbose_name='Текст')
    text = models.TextField(verbose_name='Текст', blank=True, null=True)
    target = models.TextField(verbose_name='Цель', blank=True, null=True)
    theme = models.TextField(verbose_name='Тема', blank=True, null=True)
    article_id = models.PositiveIntegerField(
        verbose_name='ID статьи', null=True)
    comment_id = models.PositiveIntegerField(
        verbose_name='ID комментария', null=True)
    like_id = models.PositiveIntegerField(verbose_name='ID лайка', null=True)
    complaint_id = models.PositiveIntegerField(
        verbose_name='ID жалобы', null=True)
    add_datetime = models.DateTimeField('Время уведомления', auto_now_add=True)

    def __str__(self):
        return f'Уведомление: {self.text}'

    class Meta:
        verbose_name = 'Уведомление'
        verbose_name_plural = 'Уведомления'

authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django_summernote.widgets import SummernoteWidget
from authapp.models import IntergalacticUser


class IntergalacticUserLoginForm(AuthenticationForm):
    class Meta:
        model = IntergalacticUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(IntergalacticUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class IntergalacticUserRegisterForm(UserCreationForm):
    class Meta:
        model = IntergalacticUser
        fields = (
            'username',
            'first_name',
            'password1',
            'password2',
            'email',
            'age',
            'sex',
            'about_me',
            'avatar'
        )
        widgets = {
            'about_me': SummernoteWidget(),
        }

    def __init__(self, *args, **kwargs):
        super(IntergalacticUserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            self.fields[field_name].help_text = None


class IntergalacticUserEditForm(UserChangeForm):
    class Meta(object):
        model = IntergalacticUser
        fields = ('username', 'first_name', 'about_me', 'email', 'age', 'avatar')
        widgets = {
            'about_me': SummernoteWidget(),
        }

    def __init__(self, *args, **kwargs):
        super(IntergalacticUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

authapp/views.py
import time
from time import sleep

from compat import JsonResponse
from django.contrib import auth
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.urls import reverse, reverse_lazy
from authapp.forms import IntergalacticUserLoginForm, IntergalacticUserRegisterForm, IntergalacticUserEditForm
from django.views.generic import FormView, ListView
from django.views.generic.base import View
from django.db import transaction

from authapp.models import NotificationModel, IntergalacticUser
from authapp.services.notifications import Notification
from mainapp.models import Article, ArticleStatus
from mainapp.forms import ArticleCreationForm
from moderation.models import BlockedUser
from moneyapp.models import UserBalance
from userprofile.models import Message, NewMessage


class LoginView(FormView):
    template_name = 'authapp/login.html'
    form_class = IntergalacticUserLoginForm
    success_url = reverse_lazy('main')

    def form_valid(self, form):
        username = self.request.POST['username']
        password = self.request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            # if not UserBalance.objects.filter(user_id=user.id):
            #     new_balance = UserBalance.objects.create(user_id=user.id)
            #     new_balance.save()
            blocked = BlockedUser.objects.all()
            if blocked:
                for b_usr in blocked:
                    if b_usr.user == user:
                        return redirect('auth:blocked')
                    else:
                        auth.login(self.request, user)
            else:
                auth.login(self.request, user)


        return super().form_valid(form)


class BlockedView(View):
    template_name = 'authapp/blocked.html'
    model = BlockedUser

    def get(self, request):
        return render(request, self.template_name)


class LogoutView(View):
    redirect_to = 'main'

    def get(self, request):
        auth.logout(request)
        return HttpResponseRedirect(reverse(self.redirect_to))


class RegisterView(FormView):
    title = 'регистрация'
    template_name = 'authapp/register.html'
    form_class = IntergalacticUserRegisterForm
    success_url = reverse_lazy('main')
    redirect_with_args = ['successful_register']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context

    def form_valid(self, form):
        form.save()

        return HttpResponseRedirect(reverse('auth:login'))


class UserEditView(View):
    title = 'редактирование'
    template_name = 'authapp/edit.html'
    redirect_to = 'profile:main'
    account_form = IntergalacticUserEditForm

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self):
        context = {
            'title': self.title,
            'form': self.account_form(instance=self.request.user),
        }
        return context

    @transaction.atomic
    def post(self, request):
        edit_account_form = self.account_form(data=request.POST, files=request.FILES, instance=request.user)
        if edit_account_form.is_valid():
            edit_account_form.save()
            return HttpResponseRedirect(reverse(self.redirect_to))

    def get(self, request):
        return render(request, self.template_name, self.get_context_data())


def reading_notifications(func):
    def wrapper(self, request, **kwargs):
        res = func(self, request, **kwargs)
        notifications_not_read = NotificationModel.objects.filter(recipient_id=self.request.user.id, is_read=0)
        for item in notifications_not_read:
            item.is_read = 1
            item.save()
        return res

    return wrapper


class NotificationView(ListView):
    title = 'Уведомления'
    template_name = 'authapp/notifications.html'
    ordering = ['-add_datetime']

    def get_context_data(self, **kwargs):
        notifications_not_read = NotificationModel.objects.filter(recipient_id=self.request.user.id, is_read=0)
        notifications_read = NotificationModel.objects.filter(recipient_id=self.request.user.id, is_read=1)

        context = {
            'title': self.title,
            'user': self.request.user,
            'notifications_not_read': notifications_not_read.order_by('-add_datetime'),
            'notifications_read': notifications_read.order_by('-add_datetime')
        }
        return context

    @reading_notifications
    def get(self, request, **kwargs):
        return render(request, self.template_name, self.get_context_data())


def notifications_live(request, count):
    for _ in range(30):
        notifications_live_count = NotificationModel.objects.filter(recipient_id=request.user.id, is_read=0).count()
        if notifications_live_count > count:
            notification_last = NotificationModel.objects.filter(recipient_id=request.user.id, is_read=0).order_by('-add_datetime').first()
            result = {
                'notifications_live_count': notifications_live_count,
                'notification_last_time': time.ctime(),
                'notification_theme': notification_last.theme
            }
            return JsonResponse(result)
        sleep(1)
    return JsonResponse({'notifications_live_count': 'retry'})


def messages_live(request, count):
    for _ in range(30):
        messages_live_count = NewMessage.objects.filter(to_user=request.user).count()
        if messages_live_count > count:
            result = {
                'messages_live_count': messages_live_count,
                'messages_last_time': time.ctime(),
                'messages_theme': 'Сообщение'
            }
            return JsonResponse(result)
        sleep(1)
    return JsonResponse({'messages_live_count': 'retry'})

authapp/templates/authapp/blocked.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,minimum-scale=1,maximum-scale=10">
         {% block stylesheets %}
            {% include 'mainapp/includes/inc_stylesheets.html' %}
         {% endblock stylesheets %}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <section class="main-content blockedtext">
            Ваш аккаунт заблокирован

        </section>

        {% block footer %}
            {% include 'mainapp/includes/inc__footer.html' %}
        {% endblock %}


    </body>
</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}
{% load project_tags %}

{% block content %}
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'hub_category' 0 %}" class="">
            на главную
        </a>
    </button>
    <div class="user_avatar"><img src="{{ user.avatar|media_folder_users }}"></div>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <div class="login-box">
        <div style="margin-bottom: 15%; text-align: center; display: flex; align-items: center">
            <div style="display:inline-block; width: 25%;">
                <img src="{% static 'img/logo.png' %}" style="" width="40" height="40" class="d-inline-block align-top"
                     alt="">
            </div>
            <div style="display:inline-block; width: 65%">
                <h3 class="text-center" style=" color: #6c757d;">Intergalactic Entertainment</h3>
            </div>
        </div>
        <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            {% if next %}
                <input type="hidden" name="next" value="{{ next }}">
            {% endif %}
            <input class="form-control" type="submit" value="Войти">
        </form>

        <button class="btn btn-round form-control">
            <a id="register" href="{% url 'auth:register' %}" class="">
                Зарегистрироваться
            </a>
        </button>
        <div class="soc-box">
            <p>Авторизация через:</p>
            <div class="soc-buttons">
                <a href="/login/vk-oauth2">
                    <img alt="VK" src="{% static 'img/vk_logo.svg' %}" class="soc-icon" data-toggle="tooltip" title="VK">
                </a>
                <a href="{% url 'social:begin' 'github' %}?next=/">
                    <img alt="Github" src="{% static 'img/github_logo.svg' %}"
                         class="soc-icon" data-toggle="tooltip" title="Github">
                </a>
{#                <a href="{% url 'social:begin' 'google-oauth2' %}"><img src="{% static 'img/google_logo.png' %}"#}
{#                                                                class="soc-icon" data-toggle="tooltip" title=""></a>#}
            </div>
        </div>
    </div>


{% endblock %}

authapp/templates/authapp/notifications.html
{% extends "mainapp/base.html" %}
{% load static %}
{% load project_tags %}
{% block title %}{{ title|title }}{% endblock %}
{% block content %}
{% if not notifications_not_read and not notifications_read %}
<h3 class="display-heading text-center">Уведомлений пока что нет...</h3>
{% else %}
<div class="article-box">
    {% if notifications_not_read %}
    <h3>Новые уведомления: </h3>
    {% for item in notifications_not_read %}
    <div class="block-notification">
        {{ item.add_datetime }}
        {% if item.sender %}
            <a href="{% url 'profile:user' item.sender.id %}">
                <span class="font-weight-bold">
                    {{item.sender }}
                </span>
            </a>
        {% endif %}
        {{ item.action }}
        {% if item.action == 'для публикации требуется иправить(доработать) статью ' or item.action == 'отправил на модерацию статью ' or item.action == 'оставил сообщение при модерации статьи ' %}
            <a href="{% url 'moderation:article' item.article_id %}">
        {% elif item.action == 'подал жалобу на статью: ' or item.action == 'оставил сообщение при обжаловании статьи '  %}
            <a href="{% url 'moderation:complaint' item.complaint_id %}">
        {% elif item.action == 'подал жалобу на комментарий: ' %}
            <a href="{% url 'article_page' item.article_id %}#{{item.comment_id}}">
        {% elif item.action == 'оставил комментарий к статье ' %}
            <a href="{% url 'article_page' item.article_id %}#{{item.comment_id}}">
        {% elif item.article_id %}
            <a href="{% url 'article_page' item.article_id %}">
        {% endif %}
            {% if item.target %}
                <span class="font-weight-bold">
                    {{ item.target }}
                </span>
            {% endif %}
            </a>
        {% if item.text %}
            <hr>
            {{ item.text }}
        {% endif %}
    </div>
    {% endfor %}
    {% endif %}
    <hr>
    {% if notifications_read %}
    <h3>Ранее прочитанные: </h3>
    {% for item in notifications_read %}
    <div class="block-notification">
        {{ item.add_datetime }}
        {% if item.sender %}
            <a href="{% url 'profile:user' item.sender.id %}">
                <span class="font-weight-bold">
                    {{item.sender }}
                </span>
            </a>
        {% endif %}
        {{ item.action }}
        {% if item.action == 'для публикации требуется иправить(доработать) статью ' or item.action == 'отправил на модерацию статью ' or item.action == 'оставил сообщение при модерации статьи ' %}
            <a href="{% url 'moderation:article' item.article_id %}">
        {% elif item.action == 'подал жалобу на статью: ' or item.action == 'оставил сообщение при обжаловании статьи '  %}
            <a href="{% url 'moderation:complaint' item.complaint_id %}">
        {% elif item.action == 'подал жалобу на комментарий: ' %}
            <a href="{% url 'article_page' item.article_id %}#{{item.comment_id}}">
        {% elif item.action == 'оставил комментарий к статье ' %}
            <a href="{% url 'article_page' item.article_id %}#{{item.comment_id}}">
        {% elif item.article_id %}
            <a href="{% url 'article_page' item.article_id %}">
        {% endif %}
            {% if item.target %}
                <span class="font-weight-bold">
                    {{ item.target }}
                </span>
            {% endif %}
            </a>
        {% if item.text %}
            <hr>
            {{ item.text }}
        {% endif %}
    </div>
    {% endfor %}
    {% endif %}
</div>
{% endif %}
{% endblock %}

authapp/templates/authapp/profile.html
{% extends "mainapp/base.html" %}
{% load static %}
{% block title %}{{ title|title }} {% endblock %}
{% load project_tags %}
{% block content %}
    <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
    <div class="article-box">
        <div class="details">
            <h3 class="text-center profile_subheading_1">Личный кабинет</h3>
            <div class="block-article">
                <div class="block-profile">
                    <div class="img-role-redaction-block">
                        <div class="profile-img-block">
                            <img class="profile_image" src="{{ user.avatar|media_folder_users }}"
                                  alt="profile_image">
                        </div>
                        <div class="profile-role-block">
                            {% if user.is_superuser %}
                                Администратор
                            {% elif user.is_staff %}
                                Модератор
                            {% else %}
                                Пользователь
                            {% endif %}
                        </div>
                        <div class="user-admin-moder-buttons">
                            <a class="btn-red-profile-block" href="{% url 'auth:edit' %}">
                                Редактировать профиль
                            </a>

                            <div class="admin-moder-buttons">
                                {% if user.is_superuser %}
                                    <hr>
                                    <div class="btn-profile-admin-block">
                                        <a class="btn-red-profile-block" href="{% url 'adminapp:users' %}">Админка</a>
                                        <a class="btn-red-profile-block" href="{% url 'moderation:main' %}">Модерация</a>
                                    </div>
                                {% elif user.is_staff %}
                                    <div><a class="btn btn-secondary" href="{% url 'moderation:main' %}">Модерация</a></div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="info-about-user">
                        <div class="first-last-name-block">
                            <p class="first-last-name">{{ user.first_name|title }} {{ user.last_name|title }}</p>

                        </div>
                        <hr>
                        <div class="profile_info">
                            <div class="profile_about">
                                <p><span class="about-user-pole">Username:</span> {{ user.username }}</p>
                                <hr>
                                <p><span class="about-user-pole">Возраст:</span> {{ user.age }}</p>
                                <hr>
                                <p><span class="about-user-pole">Обо мне:</span>
                                    {% if user.about_me %}
                                        {{ user.about_me|safe }}
                                    {% else %}
                                        Тут могла бы быть информация о вас, но вы не заполнили профиль =(
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="my-articles">
                <div class="my-articles-item">
                    <h3 class="profile_subheading_1 text-center">
                        Мои статьи
                    </h3>
                </div>
                <div class="my-articles-item">
                    <button type="button" class="btn-create-article" data-toggle="modal" data-target="#createArticle">
                        +
                    </button>
                </div>
            </div>
            <div class="block-article">
                <div class="profile-article">
                    <p class="profile_subheading_2"></p>
                </div>

                <div class="modal fade" id="createArticle" data-backdrop="static" data-keyboard="false" tabindex="-1"
                     aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog modal-xl modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="staticBackdropLabel">Новая статья</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form class="form-horizontal" action="{% url 'profile:create_article' %}" method="post"
                                      enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ creation_form.as_table }}
                                    <br>
                                    <input class="form-control" type="submit" value="Сохранить">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                {% for status, arts in articles.items %}
                    <p class="profile_subheading_2">{{ status.name_plural }}</p>
                    {% if not arts %}
                        <p>Нет статей</p>
                    {% else %}
                        <table class="article-table">
                            <tbody>
                            {% for art in arts %}
                                <tr>
                                    <td class="article-table">
                                        <table>
                                            <tr>
                                                <td rowspan="2" class="article-name">
                                                    {% if art.article_status_new.name == 'Опубликована' %}

                                                        <a href="{% url 'article_page' art.pk %}" class="article-anchor">
                                                            <p>{{ art.name }}</p>
                                                        </a>
                                                    {% elif art.article_status_new.name == 'На модерации' %}
                                                    <a href="{% url 'moderation:article' art.pk %}" class="article-anchor">
                                                        <p>{{ art.name }}</p>
                                                    </a>
                                                    {% else %}
                                                    <p>{{ art.name }}</p>
                                                    {% endif %}

                                                </td>
                                                <td class="hub-name"><p>{{ art.hub.name }}</p></td>
                                                <td rowspan="2" class="article-edit-buttons">
                                                    {% for button in status.buttons.all %}
                                                        {% include button.include_html_file_name %}
                                                    {% endfor %}
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="hub-name"><p>{{ art.add_datetime }}</p></td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <script src="{% static 'js/profile_articles.js' %}"></script>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <div class="register-form">
        <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input id="register" class="form-control" type="submit" value="зарегистрироваться">
        </form>
        <a class="btn btn-outline-success" style="width: 100%; margin-top: 10px" href="{% url 'auth:login' %}">Вход</a>
        <a class="btn btn-outline-primary" style="width: 100%; margin-top: 10px" href="{% url 'main' %}">На главную</a>
    </div>
{% endblock %}