authapp/urls.py
from django.urls import path

import authapp.views as authapp


app_name = 'auth'

urlpatterns = [
    path('login/', authapp.LoginView.as_view(), name='login'),
    path('logout/', authapp.LogoutView.as_view(), name='logout'),
    path('register/', authapp.RegisterView.as_view(), name='register'),
    path('edit/', authapp.UserEditView.as_view(), name='edit'),
    path('notifications/', authapp.NotificationView.as_view(), name='notifications'),
    path('blocked/', authapp.BlockedView.as_view(), name='blocked'),
    path('notifications_live/<int:count>/', authapp.notifications_live, name='notifications_live'),
    path('messages_live/<int:count>/', authapp.messages_live, name='messages_live'),
]

intergalactic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path



urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('profile/', include('userprofile.urls', namespace='profile')),
    path('blog_admin/', include('adminapp.urls', namespace='adminapp')),
    path('moderation/', include('moderation.urls', namespace='moderation')),
    path('moneyapp/', include('moneyapp.urls', namespace='moneyapp')),
    path('', include('social_django.urls', namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

moderation/urls.py
from django.urls import path
from moderation.views import Moderator, ModerationArticleView, RegisterNewMessage, ApproveArticle, RejectArticle, ModerateComplaints, ModerationArticleComplaintView, RegisterNewComplaintMessage

from moderation.views import BlockedArticle

app_name = 'moderation'

urlpatterns = [
    path('', Moderator.as_view(), name='main'),
    path('article/<int:pk>/', ModerationArticleView.as_view(), name='article'),
    path('new_message/', RegisterNewMessage.as_view(), name='new_message'),
    path('approve_article/<int:pk>/',
         ApproveArticle.as_view(), name='approve_article'),
    path('reject_article/<int:pk>/',
         RejectArticle.as_view(), name='reject_article'),
    path('blocked_article/<int:pk>/', BlockedArticle.as_view(), name='blocked_article'),
    path('new_complaint_message/', RegisterNewComplaintMessage.as_view(),
         name='new_complaint_message'),
    path('complaints', ModerateComplaints.as_view(), name='complaints'),
    path('complaint/<int:pk>/',
         ModerationArticleComplaintView.as_view(), name='complaint'),

]

moderation/models.py
from django.db import models

from authapp.models import IntergalacticUser
from mainapp.models import Article, Comment


class ArticleMessage(models.Model):
    article = models.ForeignKey(
        Article, verbose_name='Статья', on_delete=models.CASCADE)
    message_from = models.ForeignKey(
        IntergalacticUser,
        verbose_name='Сообщение от',
        null=True,
        on_delete=models.SET_NULL
    )
    text = models.TextField(verbose_name='Текст сообщения')
    moderator = models.ForeignKey(
        IntergalacticUser,
        verbose_name='Модератор',
        null=True,
        on_delete=models.SET_NULL,
        related_name='moderator'
    )
    datetime = models.DateTimeField(
        verbose_name='Дата и время сообщения', auto_now_add=True)


class BlockedUser(models.Model):
    user = models.OneToOneField(
        IntergalacticUser, verbose_name='Пользователь', related_name='blusers', on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Причина блокировки', blank=True)
    datetime = models.DateTimeField(verbose_name='Дата и время блокировки', auto_now_add=True)

    def __str__(self):
        return f'{self.user}'


class Complaint(models.Model):
    article = models.ForeignKey(
        Article, verbose_name='Статья', null=True, on_delete=models.CASCADE)
    comment = models.ForeignKey(
        Comment, null=True, verbose_name='Комментарий', on_delete=models.CASCADE)
    complainant = models.ForeignKey(
        IntergalacticUser,
        verbose_name='Жалоба от',
        null=True,
        on_delete=models.SET_NULL
    )
    text = models.TextField(verbose_name='Текст жалобы')
    datetime = models.DateTimeField(
        verbose_name='Дата и время жалобы', auto_now_add=True)
    is_active = models.BooleanField(
        verbose_name='Актуальность жалобы',
        default=True,
        db_index=True,
    )

    class Meta:
        verbose_name = 'жалоба'
        verbose_name_plural = 'жалобы'
        ordering = ['-datetime']


class ComplaintMessage(models.Model):
    complaint = models.ForeignKey(
        Complaint, verbose_name='Жалоба', on_delete=models.CASCADE)
    article = models.ForeignKey(
        Article, verbose_name='Статья', null=True, on_delete=models.CASCADE)
    comment = models.ForeignKey(
        Comment, verbose_name='Комментарий', null=True, on_delete=models.CASCADE)
    message_from = models.ForeignKey(
        IntergalacticUser,
        verbose_name='Сообщение от',
        null=True,
        on_delete=models.SET_NULL
    )
    text = models.TextField(verbose_name='Текст сообщения')
    datetime = models.DateTimeField(
        verbose_name='Дата и время сообщения', auto_now_add=True)

moderation/views.py
import json
from datetime import datetime
from pprint import pp, pprint

from django.contrib.auth.decorators import user_passes_test
from django.http import JsonResponse, request
from django.views.generic.base import View
from django.views.generic.list import ListView
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator

from authapp.models import NotificationModel
from authapp.services.notifications import Notification
from mainapp.models import Article, ArticleStatus
from moderation.models import ArticleMessage, Complaint, ComplaintMessage
from django.db import models


class ModerationMixin(View):
    """Это проверка, что пользователь является админимстратором или модератором.
    Все классы отнаследованные от него, наследуют эту проверку."""

    @method_decorator(user_passes_test(lambda u: u.is_superuser or u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        if request.method.lower() in self.http_method_names:
            handler = getattr(self, request.method.lower(),
                              self.http_method_not_allowed)
        else:
            handler = self.http_method_not_allowed
        return handler(request, *args, **kwargs)


class Moderator(ModerationMixin, ListView):
    model = Article
    template_name = 'moderation/moderator.html'
    paginate_by = 5


#    def get_queryset(self):
#        queryset = Article.objects.filter(
#            article_status_new=ArticleStatus.objects.get(name='На модерации'))
#        return queryset # ie-178 Dmitrij

    def get_context_data(self, **kwargs):
        context = super(Moderator, self).get_context_data(**kwargs)
        context['title'] = 'модератор'
        context['objects_list'] = Article.objects.filter(
            article_status_new=ArticleStatus.objects.get(name='На модерации'))
        context['notifications_not_read'] = NotificationModel.objects.filter(is_read=0,
                                                                             recipient=self.request.user.id).count()
        context['blocked'] = Article.objects.filter(
            article_status_new=ArticleStatus.objects.get(short_name='AB'))

        return context


class ModerationArticleView(View):
    template_name = 'moderation/article_page.html'

    def get_context_data(self, pk):
        context = {
            'title': 'Статья',
            'user': self.request.user,
            'article': get_object_or_404(Article, pk=pk),
            'messages': ArticleMessage.objects.filter(article=Article.objects.get(pk=pk)).order_by('-datetime'),
            'notifications_not_read': NotificationModel.objects.filter(is_read=0,
                                                                       recipient=self.request.user.id).count()
        }
        return context

    def get(self, request, pk):
        if self.request.user.is_authenticated and (self.request.user == Article.objects.get(
                pk=pk).author or self.request.user.is_superuser or self.request.user.is_stuff):
            return render(request, self.template_name, self.get_context_data(pk))

        return render(request, 'moderation/err_article_on_moderation.html', self.get_context_data(pk))


class RegisterNewMessage(View):
    def post(self, request):
        if request.is_ajax():
            ajax = json.loads(request.body.decode('utf-8'))
            message = ArticleMessage(
                article=Article.objects.get(pk=ajax.get('article')),
                message_from=request.user,
                text=ajax.get('text')
            )
            message.save()
            notification = Notification(message)
            notification.send()
            result = {
                'author': message.message_from.username,
                'datetime': message.datetime.strftime('%d-%m-%Y %H:%M'),
                'text': message.text
            }
            return JsonResponse(result)


class ApproveArticle(ModerationMixin):
    def get(self, request, pk):
        article = get_object_or_404(Article, pk=pk)
        article.article_status_new = ArticleStatus.objects.get(
            name='Опубликована')
        article.save()
        notification = Notification(article, context='published')
        notification.send()
        return HttpResponseRedirect(reverse_lazy('moderation:main'))


class RejectArticle(ModerationMixin):
    def get(self, request, pk):
        article = get_object_or_404(Article, pk=pk)
        article.article_status_new = ArticleStatus.objects.get(
            name='Требует исправления')
        article.save()
        notification = Notification(article, context='rejected')
        notification.send()
        return HttpResponseRedirect(reverse_lazy('moderation:main'))


class BlockedArticle(ModerationMixin):
    def get(self, request, pk):
        article = get_object_or_404(Article, pk=pk)
        article.article_status_new = ArticleStatus.objects.get(name='Заблокирована')
        article.is_active = False
        article.save()
        notification = Notification(article, context='blocked')
        notification.send()
        return HttpResponseRedirect(reverse_lazy('moderation:main'))


class ModerateComplaints(ModerationMixin, ListView):
    model = Complaint
    template_name = 'moderation/moderate_complaints.html'
    # extra_context = {'title': 'Модератор'}
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(ModerateComplaints, self).get_context_data(**kwargs)
        context['title'] = 'модератор'
        context['objects_list'] = Complaint.objects.filter(
            is_active=True).order_by('-datetime')
        context['notifications_not_read'] = NotificationModel.objects.filter(is_read=0,
                                                                             recipient=self.request.user.id).count()
        return context


class ModerationArticleComplaintView(View):
    template_name = 'moderation/article_complaint_page.html'

    def get_context_data(self, pk):
        # article = get_object_or_404(Article, pk=pk)
        # article = Complaint.objects.get(pk=pk).article
        # complainant = Complaint.objects.get(pk=pk).complainant
        context = {
            'title': 'Статья',
            'user': self.request.user,
            'article': Complaint.objects.get(pk=pk).article,
            'complainant': Complaint.objects.get(pk=pk).complainant,
            'messages': ComplaintMessage.objects.filter(complaint=pk).order_by('-datetime'),
            'notifications_not_read': NotificationModel.objects.filter(is_read=0, recipient=self.request.user.id).count()
        }
        return context

    def get(self, request, pk):
        # article = Complaint.objects.get(pk=pk).article
        complainant = Complaint.objects.get(pk=pk).complainant
        # if self.request.user.is_authenticated and (self.request.user == Complaint.objects.get(pk=pk).article.author or self.request.user.is_superuser or self.request.user == complainant):
        if self.request.user.is_authenticated and (self.request.user.is_superuser or self.request.user == complainant):
            return render(request, self.template_name, self.get_context_data(pk))

        return render(request, 'moderation/err_article_on_moderation.html', self.get_context_data(pk))


class RegisterNewComplaintMessage(View):
    def post(self, request):
        if request.is_ajax():
            ajax = json.loads(request.body.decode('utf-8'))
            article = Article.objects.get(pk=ajax.get('article'))
            complaint = Complaint.objects.filter(article=article).last()
            message = ComplaintMessage(
                complaint=complaint,
                article=article,
                message_from=request.user,
                text=ajax.get('text')
            )
            message.save()
            notification = Notification(message)
            notification.send()
            result = {
                'author': message.message_from.username,
                'datetime': message.datetime.strftime('%d-%m-%Y %H:%M'),
                'text': message.text
            }
            return JsonResponse(result)

moderation/templates/moderation/article_complaint_page.html
{% extends "mainapp/base.html" %}
{% load project_tags %}
{% load static %}
{% block title %}{{ page_title|title }} {{ article.pk }}: {{ article }}{% endblock %}
{% block content %}
<div class="moderation-article-box">
    {% csrf_token %}
    <div class="details">
        <div class="moderation-details-articles">
            <h4 class="text-center">{{ article.name }}</h4>
            <div class="img-box">
                <img class="img-thumbnail" src="{{ article.image|media_folder_article }}" alt="">
            </div>
            <div class="text">
                <p>{{ article.add_datatime }}</p>
                {{ article.text|safe|linebreaks }}
                <hr>
                <p>#{{ article.tag }}</p>
                <p>{{ article.hub }}</p>
            </div>
        </div>
    </div>
    <div class="card mb-3 moderation-chat">
        <div class="card-header">
            {% if user.is_stuff or user.is_superuser %}
            <p>Общение с подателем жалобы ({{ complainant|title }})</p>
            {% else %}
            <p>Общение с Модератором</p>
            {% endif %}
            {% if user.is_stuff or user.is_superuser %}
            {% if article.article_status_new.short_name == 'PB' %}
            <a class="btn btn-primary btn-sm" href="{% url 'moderation:reject_article' article.pk %}"
                role="button">Снять с публикации</a>
            {% else %}
            <p style="color:red"><i> Статья снята с публикации</i></p>
            {% endif %}
            {% endif %}
        </div>
        <div class="card-body">
            <div class="input-group mb-3">
                <textarea class="form-control" placeholder="Введите сообщение сюда" aria-label="Recipient's username"
                    aria-describedby="send_message" id="message"></textarea>
                <button class="btn btn-outline-secondary" type="button" id="send_message"
                    name="{{ article.pk }}">Отправить</button>
            </div>
            <div class="moderation-messages">

                {% for message in messages %}
                {% if user.pk == message.message_from.pk %}
                <div class="complaint-message" style="background-color: springgreen; margin-left: 5%;">
                    {% else %}
                    <div class="complaint-message" style="background-color: thistle; margin-right: 5%;">
                        {% endif %}
                        <div class="first-line">
                            <div class="author">
                                {% if message.message_from.is_stuff or message.message_from.is_superuser %}
                                <p>{{ message.message_from.username|title }} (модератор)</p>
                                {% else %}
                                <p>{{ message.message_from.username|title }}</p>
                                {% endif %}
                            </div>
                            <div class="datetime">
                                <p>{{ message.datetime | date:"d-m-Y H:i" }}</p>
                            </div>
                        </div>
                        <div class="second-line">
                            <p>{{ message.text }}</p>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/moderate_complaints.js' %}"></script>
    {% endblock %}

moderation/templates/moderation/article_page.html
{% extends "mainapp/base.html" %}
{% load project_tags %}
{% load static %}
{% block title %}{{ page_title|title }} {{ article.pk }}: {{ article }}{% endblock %}
{% block content %}
    <div class="moderation-article-box">
    {% csrf_token %}
        <div class="details">
            <div class="moderation-details-articles">
                <h4 class="text-center">{{ article.name }}</h4>
                <div class="img-box">
                    <img class="img-thumbnail" src="{{ article.image|media_folder_article }}" alt="">
                </div>
                <div class="text">
                    <p>{{ article.add_datatime }}</p>
                    {{ article.text|safe|linebreaks }}
                    <hr>
                    <p>#{{ article.tag }}</p>
                    <p>{{ article.hub }}</p>
                </div>
            </div>
        </div>
        <div class="card mb-3 moderation-chat">
            <div class="card-header">
                {% if user.is_stuff or user.is_superuser %}
                    <p>Общение с автором ({{ article.author.username }})</p>
                {% else %}
                    <p>Общение с Модератором</p>
                {% endif %}
                {% if user.is_stuff or user.is_superuser %}
                <a class="btn btn-primary btn-sm" href="{% url 'moderation:approve_article' article.pk %}" role="button">Разрешить публикацию</a>
                <a class="btn btn-primary btn-sm" href="{% url 'moderation:reject_article' article.pk %}" role="button">Вернуть на доработку</a>
                <a class="btn btn-primary btn-sm" href="{% url 'moderation:blocked_article' article.pk %}" role="button">Заблокировать</a>
                {% endif %}
            </div>
            <div class="card-body">
                <div class="input-group mb-3">
                    <textarea class="form-control" placeholder="Recipient's username"
                              aria-label="Recipient's username" aria-describedby="send_message" id="message"></textarea>
                    <button class="btn btn-outline-secondary" type="button" id="send_message" name="{{ article.pk }}">Отправить</button>
                </div>
                {% if not messages %}
                <p class="card-text" id="no_message">
                    Пока нет ни одного сообщения.
                </p>
                {% endif %}

                <div class="moderation-messages">
                    {% if not messages %}
                    <div class="moderation-message"></div>
                    {% else %}
                    {% for message in messages %}
                    <div class="moderation-message">
                        <div class="first-line">
                            <div class="author">
                                <p>{{ message.message_from.username }}</p>
                            </div>
                            <div class="datetime">
                                <p>{{ message.datetime | date:"d-m-Y H:i" }}</p>
                            </div>
                        </div>
                        <div class="second-line">
                            <p>{{ message.text }}</p>
                        </div>
                    </div>
                    {% endfor %}

                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/moderation.js' %}"></script>
{% endblock %}

moderation/templates/moderation/err_article_on_moderation.html
{% extends "mainapp/base.html" %}
{% load project_tags %}
{% load static %}
{% block title %}{{ page_title|title }}{% endblock %}
{% block content %}
    <div class="moderation-article-box">
        <div class="details">
            <div class="details-articles">
                <h4 class="text-center">Статья находится на модерации</h4>
            </div>
        </div>
    </div>
{% endblock %}

moderation/templates/moderation/moderate_complaints.html
{% extends "mainapp/base.html" %}
{% comment %} {% load project_tags %} {% endcomment %}

{% block title %}{{ title|title }}{% endblock %}
{% block content %}
<div class="article-box">
    <h1>Панель модератора</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
        </script>

    <ul class="nav nav-pills mb-3">
        <li class="nav-item"><a href="{% url 'moderation:main' %}" class="btn btn-secondary btn-sm active mx-2" role="button"
                aria-disabled="true">Статьи на
                проверку</a></li>
        <li class="nav-item"></li><a href="{% url 'moderation:complaints' %}" class="btn btn-secondary btn-sm disabled active mx-2"
            role="button" aria-pressed="true">Жалобы
            пользователей</a></li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab"
            style="background: none !important;">
            <table>
                <tbody>
                    {% for complaint in object_list %}
                    <tr>
                        <td>
                            <div class="block-moder-article"  style="width: 696px">
                                <table>
                                    <tr>
                                        <td colspan="2">
                                            {% if complaint.comment %}
                                            <a href="{% url 'article_page' complaint.article.id %}#{{complaint.comment.pk}}"
                                                class="article-anchor">
                                                {% else %}
                                                <a href="{% url 'moderation:complaint' complaint.pk %}"
                                                    class="article-anchor">
                                                    {% endif %}
                                                    <p><b><i>ЖАЛОБА:</i></b> &nbsp &nbsp {{ complaint.text }}</p>
                                                </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="hub-name">
                                            <p><i>ПОДАЛ:</i> &nbsp &nbsp {{ complaint.complainant|title }}<br>
                                                {{ complaint.datetime }}
                                            </p>
                                        </td>
                                        <td class="article-name">
                                            {% if complaint.comment %}
                                            <a href="{% url 'article_page' complaint.article.id %}#{{complaint.comment.pk}}"
                                                class="article-anchor">
                                                <p><i><u>НА КОММЕНТАРИЙ:</u></i><br> {{ complaint.comment.text }}</p>
                                                <p><i>К СТАТЬЕ:</i><br> {{ complaint.article.name }}</p>
                                            </a>
                                            {% else %}
                                            <a href="{% url 'moderation:complaint' complaint.pk %}"
                                                class="article-anchor">
                                                <p><i><u>НА СТАТЬЮ:</u></i><br> {{ complaint.article.name }}</p>
                                            </a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

moderation/templates/moderation/moderator.html
{% extends "mainapp/base.html" %}
{% comment %} {% load project_tags %} {% endcomment %}

{% block title %}{{ title|title }}{% endblock %}
{% block content %}

<body>
    <div class="article-box">
        <h1>Панель модератора</h1>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
            </script>

        <ul class="nav nav-pills mb-3">
            <li class="nav-item"><a href="{% url 'moderation:main' %}" class="btn btn-secondary btn-sm disabled active mx-2"
                    role="button" aria-disabled="true">Статьи на
                    проверку</a></li>
            <li class="nav-item"><a href="{% url 'moderation:complaints' %}" class="btn btn-secondary btn-sm active mx-2"
                    role="button" aria-pressed="true">Жалобы
                    пользователей</a></li>
        </ul>
        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab"
                style="background: none !important;">
                <table>
                    <tbody>
                        {% for article in objects_list %}
                        <tr>
                            <td>
                                <div class="block-moder-article">
                                    <table>
                                        <tr>
                                            <td rowspan="2" class="article-name">
                                                <a href="{% url 'moderation:article' article.pk %}"
                                                    class="article-anchor">
                                                    <p>{{ article.name }}</p>
                                                </a>
                                            </td>
                                            <td class="hub-name">
                                                <p>{{ article.hub.name }}</p>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="hub-name">
                                                <p>{{ article.add_datetime }}</p>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    <p class="profile_subheading_2">Заблокированные статьи: </p>
        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" style="background: none !important;">
                <table>
                    <tbody>
                    {% for article in blocked %}
                        <tr>
                            <td>
                                <div class="block-moder-article" style="background-color: #ffdede; width: 696px">
                                    <table>
                                        <tr>
                                            <td rowspan="2" class="article-name">
                                                <a href="{% url 'moderation:article' article.pk %}" class="article-anchor" style="color: #707070">
                                                    <p>{{ article.name }}</p>
                                                </a>
                                            </td>
                                            <td class="hub-name" style="color: #707070"><p>{{ article.hub.name }}</p></td>

                                        </tr>
                                        <tr>
                                            <td class="hub-name" style="color: #707070"><p>{{ article.add_datetime }}</p></td>
                                        </tr>
                                    </table>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</body>
{% endblock %}